# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
---
ci:
  autofix_commit_msg: "style: pre-commit.ci auto fixes [...]"
  autoupdate_commit_msg: "chore: pre-commit autoupdate"
  autoupdate_schedule: monthly
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: trailing-whitespace
      - id: check-added-large-files
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: 'v0.6.4'
    hooks:
      - id: ruff
        args: [--fix, --exit-non-zero-on-fix]
  - repo: https://github.com/psf/black
    rev: 24.8.0
    hooks:
      - id: black
exclude: |
  (?x)^(
    vendored |
    .*/vendored
  )
