dist: xenial
sudo: required
language: python
matrix:
  include:
    - python: 3.6
      env: TOXENV=py36
    - python: 3.7
      env: TOXENV=py37
before_install:
    - sudo apt-get update
    - sudo apt-get install -y libsodium-dev
install:
    - travis_retry pip install tox
    # XXX Avoid snapcraft from loading useless libs when running on Ubuntu
    - sudo truncate -s 0 /etc/os-release
script:
    - tox
after_success:
    - tox -e coveralls
