# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.
---
loader: taskgraph.loader.transform:loader

kind-dependencies:
    - docker-image

# Copy of tox job, but doesn't use caching

transforms:
    - scriptworker_taskgraph.transforms.python_version:transforms
    - scriptworker_taskgraph.transforms.tox:transforms
    - taskgraph.transforms.job:transforms
    - taskgraph.transforms.task:transforms

jobs:
    check:
        description: "ruff-py39"
        run-on-tasks-for: ["action", "github-pull-request", "github-push"]
        attributes:
            code-review: true
        worker-type: b-linux
        worker:
            docker-image: {in-tree: 'python39'}
            max-run-time: 1800
        python-versions: [39]
        run:
            using: run-task
            cache-dotcache: false
            checkout:
                scriptworker: {}
            cwd: '{checkout}'
            command:
                - sh
                - -lxce
                - tox -e ruff-py39
