provisioner_id: scriptworker-prov-v1
worker_group: {"$eval": "WORKER_GROUP"}
worker_type: {"$eval": "WORKER_TYPE"}
worker_id: {"$eval": "WORKER_ID"}

credentials:
    clientId: {"$eval": "TASKCLUSTER_CLIENT_ID"}
    accessToken: {"$eval": "TASKCLUSTER_ACCESS_TOKEN"}

artifact_upload_timeout: 1200
task_max_timeout: 3600
task_script: [{"$eval": "TASK_SCRIPT"}, {"$eval": "TASK_SCRIPT_CONFIG"}]
verbose: true

verify_chain_of_trust: true
sign_chain_of_trust: {"$eval": "APP_CHANNEL == 'production'"}
verify_cot_signature: {"$eval": "APP_CHANNEL == 'production'"}
cot_job_type: shipit
cot_product: {"$eval": "COT_PRODUCT"}

# Calls to Github API are limited to 60 an hour. Using an API token allows to raise the limit to
# 5000 per hour. https://developer.github.com/v3/#rate-limiting
github_oauth_token: ""

log_dir: /tmp/logs
work_dir: /app/workdir
artifact_dir: /app/artifacts
task_log_dir: /app/artifacts/public/logs
watch_log_file: true

scriptworker_provisioners:
    - scriptworker-prov-v1

ed25519_private_key_path: /app/configs/ed25519_privkey
