[package]
name = "scriptworker_script_macros"
version = "0.1.0"
authors = ["Tom Prince <mozilla@hocat.ca>"]
edition = "2018"

[dependencies]
syn = {version = "1.0.5", features=["full"]}
quote = "1.0.2"

[lib]
proc-macro = true
