[package]
name = "scriptworker_script"
version = "0.1.0"
authors = ["Tom Prince <mozilla@hocat.ca>"]
edition = "2018"

[dependencies]
clap = "2.33.0"
serde_yaml = "0.8.9"
serde_json = "1.0.40"
serde = "1.0.99"
serde_derive = "1.0.99"
