work_dir: /tmp/work_dir
artifact_dir: /tmp/artifact_dir

taskcluster_scope_prefix: project:releng:treescript:

hg: hg
hg_share_base_dir: /tmp/hg_share_base
upstream_repo: https://hg.mozilla.org/mozilla-unified
treestatus_base_url: https://treestatus.mozilla-releng.net

hg_ssh_user: some_user
hg_ssh_keyfile: some_file.rsa
